export type GalleryCategory =
  | "all"
  | "tournament"
  | "summer-training"
  | "winter-program"
  | "personal-development"
  | "hiking"
  | "public-speaking";

export interface GalleryItem {
  id: string;
  title: string;
  category: GalleryCategory;
  categoryLabel: string;
  categories: GalleryCategory[];
  image: string;
  alt: string;
  aspectRatioClass: string;
  description?: string;
  date?: string;
}

export const galleryTabs: { id: GalleryCategory; label: string }[] = [
  { id: "all", label: "ALL" },
  { id: "tournament", label: "TOURNAMENT" },
  { id: "summer-training", label: "TRAINING" },
  { id: "winter-program", label: "WINTER PROGRAM" },
  { id: "personal-development", label: "PERSONAL DEVELOPMENT" },
  { id: "hiking", label: "HIKING" },
  { id: "public-speaking", label: "PUBLIC SPEAKING" },
];

export const galleryItems: GalleryItem[] = [
  // ===================== TOURNAMENTS =====================
  {
    id: "tournament-1",
    title: "Championship Tournament Action",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament1-1536x1137.webp",
    alt: "Wolverines field hockey tournament match",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "tournament-2",
    title: "Competitive Tournament Match",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament2-1-1536x1157.webp",
    alt: "Tournament match action on field",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "tournament-3",
    title: "Tournament Turf Battle",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament3-1536x1024.webp",
    alt: "Field hockey tournament battle on turf",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-4",
    title: "Offensive Drive on Goal",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament4-1536x1024.webp",
    alt: "Offensive charge towards goal during tournament",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-5",
    title: "Defensive Tackle & Recovery",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament5-1536x1024.webp",
    alt: "Clean defensive challenge in competitive match",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-6",
    title: "Midfield Transition Play",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament6-1536x1157.webp",
    alt: "Fast midfield attack transition",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "tournament-7",
    title: "Tactical Set Piece Action",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament7-1536x1024.webp",
    alt: "Penalty corner execution during tournament play",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-8",
    title: "Strikers in the Circle",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament8-1536x1024.webp",
    alt: "Strikers working inside the shooting circle",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-9",
    title: "Fast-Paced Tournament Play",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament9-1536x1024.webp",
    alt: "High energy team movement in match",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-10",
    title: "Championship Victory Moment",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament10-1536x1024.webp",
    alt: "Team celebration during tournament game",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-11",
    title: "Sideline Team Energy",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament11-1024x683.webp",
    alt: "Athletes supporting teammates from sidelines",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-12",
    title: "Tournament Medal Quest",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament12-1536x1024.webp",
    alt: "Youth tournament match playoff",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-13",
    title: "Team Strategy & Focus",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament13-1536x1024.webp",
    alt: "Team tactical execution under match pressure",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-14",
    title: "Final Whistle Passion",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament14-1536x1024.webp",
    alt: "Competitors shaking hands after tournament match",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "tournament-15",
    title: "Championship Spirit",
    category: "tournament",
    categoryLabel: "Tournament",
    categories: ["tournament"],
    image: "/gallery_img/tournament15-1536x1024.webp",
    alt: "Team displaying sportsmanship and pride",
    aspectRatioClass: "aspect-[3/2]",
  },

  // ===================== TRAINING =====================
  {
    id: "training-1",
    title: "Technical Skills & Stick Handling",
    category: "summer-training",
    categoryLabel: "Training",
    categories: ["summer-training"],
    image: "/gallery_img/training1-1024x576.webp",
    alt: "Field hockey stick control drills",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "training-2",
    title: "Speed & Footwork Conditioning",
    category: "summer-training",
    categoryLabel: "Training",
    categories: ["summer-training"],
    image: "/gallery_img/training2-1024x576.webp",
    alt: "Youth agility and footwork training",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "training-3",
    title: "Passing Precision Drills",
    category: "summer-training",
    categoryLabel: "Training",
    categories: ["summer-training"],
    image: "/gallery_img/training3-1024x576.webp",
    alt: "Passing accuracy and reception practice",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "training-4",
    title: "Shooting & Finishing Practice",
    category: "summer-training",
    categoryLabel: "Training",
    categories: ["summer-training"],
    image: "/gallery_img/training4-1024x576.webp",
    alt: "Goal finishing drills in practice session",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "training-5",
    title: "Goalkeeper Special Clinic",
    category: "summer-training",
    categoryLabel: "Training",
    categories: ["summer-training"],
    image: "/gallery_img/training5-1024x771.webp",
    alt: "Specialized goalkeeper reflexes and positioning",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "training-6",
    title: "Tactical Circle Drills",
    category: "summer-training",
    categoryLabel: "Training",
    categories: ["summer-training"],
    image: "/gallery_img/training6-1536x1157.webp",
    alt: "Coach explaining tactical setup to squad",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "training-7",
    title: "Grassroots Fundamentals Clinic",
    category: "summer-training",
    categoryLabel: "Training",
    categories: ["summer-training"],
    image: "/gallery_img/training7-1024x771.webp",
    alt: "Youth players mastering field hockey fundamentals",
    aspectRatioClass: "aspect-[4/3]",
  },

  // ===================== WINTER PROGRAM =====================
  {
    id: "winter-1",
    title: "Winter Indoor Practice Session",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter1-1024x1536.webp",
    alt: "Winter indoor gym training session",
    aspectRatioClass: "aspect-[2/3]",
  },
  {
    id: "winter-2",
    title: "Indoor Speed & Ball Control",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter2-1536x1024.webp",
    alt: "Fast indoor hockey drills",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-3",
    title: "Winter League Technical Work",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter3-1536x1024.webp",
    alt: "Winter indoor clinic techniques",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-4",
    title: "Indoor Match Scrimmage",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter4-1536x1024.webp",
    alt: "Scrimmage during winter indoor program",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-5",
    title: "Board Play & Rebound Control",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter5-1536x1024.webp",
    alt: "Athletes practicing side-board deflections",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-6",
    title: "Winter Conditioning Workout",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter6-1536x1024.webp",
    alt: "Strength and conditioning workout indoors",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-7",
    title: "Indoor Reflex & Reaction Drills",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter7-1024x1536.webp",
    alt: "High tempo reflex training session",
    aspectRatioClass: "aspect-[2/3]",
  },
  {
    id: "winter-8",
    title: "Indoor Tactical Simulation",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter8-1536x1024.webp",
    alt: "Tactical positioning on indoor court",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-9",
    title: "Indoor Defensive Positioning",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter9-1536x1024.webp",
    alt: "Defensive wall structure in indoor play",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-10",
    title: "Winter Youth Championship",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter10-1024x1536.webp",
    alt: "Athletes in action at winter indoor cup",
    aspectRatioClass: "aspect-[2/3]",
  },
  {
    id: "winter-11",
    title: "Winter League Tournament Play",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter11-1536x1024.webp",
    alt: "Winter tournament match in progress",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-12",
    title: "Dynamic Indoor Movement",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter12-1024x1536.webp",
    alt: "Indoor lateral movement and stick control",
    aspectRatioClass: "aspect-[2/3]",
  },
  {
    id: "winter-13",
    title: "Indoor Team Coordination",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter13-1536x1024.webp",
    alt: "Team sync and communication in winter session",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-14",
    title: "Winter Cup Quarterfinal Play",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter14-1536x1024.webp",
    alt: "Competitive game during winter league tournament",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-15",
    title: "Indoor Goalkeeper Reflex Save",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter15-1536x1024.webp",
    alt: "Goalkeeper making dynamic stop indoors",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-16",
    title: "Winter Trophy Presentation",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter16-1536x1024.webp",
    alt: "Medal ceremony at winter indoor tournament",
    aspectRatioClass: "aspect-[3/2]",
  },
  {
    id: "winter-17",
    title: "End-of-Season Indoor Celebration",
    category: "winter-program",
    categoryLabel: "Winter Program",
    categories: ["winter-program"],
    image: "/gallery_img/winter17-1024x1536.webp",
    alt: "Squad smiling together at close of winter season",
    aspectRatioClass: "aspect-[2/3]",
  },

  // ===================== PERSONAL DEVELOPMENT =====================
  {
    id: "dev-1",
    title: "Team Fitness & Character Building",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development1-1536x864.webp",
    alt: "Athletes participating in fitness training",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "dev-2",
    title: "Mental Resilience & Mindset Workshop",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development2-1536x864.webp",
    alt: "Youth athletes during personal development workshop",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "dev-3",
    title: "Sportsmanship & Respect Seminar",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development3-1536x864.webp",
    alt: "Coach guiding players on fair play and respect",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "dev-4",
    title: "Community Outreach & Values",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development4.webp",
    alt: "Club members giving back to the community",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "dev-5",
    title: "Leadership On and Off the Field",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development5-1536x864.webp",
    alt: "Leadership building exercises",
    aspectRatioClass: "aspect-[16/9]",
  },
  {
    id: "dev-6",
    title: "Youth Athlete Mentorship",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development6-864x1536.webp",
    alt: "Senior players mentoring junior athletes",
    aspectRatioClass: "aspect-[9/16]",
  },
  {
    id: "dev-7",
    title: "Nutrition & Athletic Health Education",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development7-1536x1157.webp",
    alt: "Athletes learning nutrition and wellness habits",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "dev-8",
    title: "Self-Discipline & Goal Setting",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development8-1157x1536.webp",
    alt: "Goal tracking and discipline exercises",
    aspectRatioClass: "aspect-[3/4]",
  },
  {
    id: "dev-9",
    title: "Team Bonding & Trust Activities",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development9-1536x1157.webp",
    alt: "Trust and teamwork group exercises",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "dev-10",
    title: "Academic & Athletic Balance",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development10-1536x1157.webp",
    alt: "Discussion on school and sports balance",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "dev-11",
    title: "Empowering Young Leaders",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development11-1157x1536.webp",
    alt: "Junior captain leading team discussion",
    aspectRatioClass: "aspect-[3/4]",
  },
  {
    id: "dev-12",
    title: "Club Pride & Integrity",
    category: "personal-development",
    categoryLabel: "Personal Development",
    categories: ["personal-development"],
    image: "/gallery_img/development12-1024x771.webp",
    alt: "Members celebrating club core values",
    aspectRatioClass: "aspect-[4/3]",
  },

  // ===================== HIKING =====================
  {
    id: "hike-1",
    title: "Abbotsford Mountain Trail Expedition",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking1 (1).webp",
    alt: "Team hiking in scenic British Columbia mountains",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-2",
    title: "Wilderness Team Trek",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking2-1024x771.webp",
    alt: "Athletes trekking along forest trail",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-3",
    title: "Summit Group Photo",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking3-1024x771.webp",
    alt: "Team gathered at mountain viewpoint",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-4",
    title: "Nature Immersion & Recovery Walk",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking4-1024x768.webp",
    alt: "Team walk through lush green cedar forest",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-5",
    title: "Trail Endurance Challenge",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking5-1024x771.webp",
    alt: "Building endurance on steep incline trail",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-6",
    title: "Alpine Adventure Memories",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking6-1024x771.webp",
    alt: "Athletes posing along scenic trail ridge",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-7",
    title: "Forest Canopy Exploration",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking7-1157x1536.webp",
    alt: "Towering trees along Pacific Northwest hiking trail",
    aspectRatioClass: "aspect-[3/4]",
  },
  {
    id: "hike-8",
    title: "Team Trail Reflection",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking8-768x1020.webp",
    alt: "Athletes taking break on hiking path",
    aspectRatioClass: "aspect-[3/4]",
  },
  {
    id: "hike-9",
    title: "Wilderness Bonding Moments",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking9-1157x1536.webp",
    alt: "Smiling faces during club nature expedition",
    aspectRatioClass: "aspect-[3/4]",
  },
  {
    id: "hike-10",
    title: "Panoramic Valley Lookout",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking10-1536x1157.webp",
    alt: "Overlooking Fraser Valley from mountain top",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-11",
    title: "Outdoor Camaraderie",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking11.webp",
    alt: "Team sharing laughter along nature path",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-12",
    title: "River Trail Adventure",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking12-1157x1536.webp",
    alt: "Crossing river stone bridge in Abbotsford",
    aspectRatioClass: "aspect-[3/4]",
  },
  {
    id: "hike-13",
    title: "Highland Forest Hike",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking13-1157x1536.webp",
    alt: "Hikers ascending highland mountain trail",
    aspectRatioClass: "aspect-[3/4]",
  },
  {
    id: "hike-14",
    title: "Team Reaching the Peak",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking14-1536x1157.webp",
    alt: "Celebration at the peak of the mountain",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-15",
    title: "Fresh Air & Open Horizons",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking15-1536x1157.webp",
    alt: "Breathtaking landscape with Wolverines team",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-16",
    title: "Trailside Group Photo",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking16-1536x1152.webp",
    alt: "Group photo beside ancient cedar stump",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-17",
    title: "Nature Appreciation Walk",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking17-1536x1157.webp",
    alt: "Youth players learning outdoor stewardship",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "hike-18",
    title: "Sunset Descent Journey",
    category: "hiking",
    categoryLabel: "Hiking",
    categories: ["hiking"],
    image: "/gallery_img/hiking18-1536x1157.webp",
    alt: "Golden hour descent down Abbotsford ridge",
    aspectRatioClass: "aspect-[4/3]",
  },

  // ===================== PUBLIC SPEAKING =====================
  {
    id: "speaking-1",
    title: "Youth Athlete Keynote Address",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking1-864x1536.webp",
    alt: "Young member giving speech at podium",
    aspectRatioClass: "aspect-[9/16]",
  },
  {
    id: "speaking-2",
    title: "Awards Ceremony Presentation",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking2-864x1536.webp",
    alt: "Athlete addressing audience at ceremony",
    aspectRatioClass: "aspect-[9/16]",
  },
  {
    id: "speaking-3",
    title: "Confidence at the Microphone",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking3.webp",
    alt: "Building confidence through public speaking",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "speaking-4",
    title: "Community Speech & Recognition",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking4-864x1536.webp",
    alt: "Player speaking on club community impact",
    aspectRatioClass: "aspect-[9/16]",
  },
  {
    id: "speaking-5",
    title: "Leadership Address",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking5-864x1536.webp",
    alt: "Senior coach and athlete addressing gathering",
    aspectRatioClass: "aspect-[9/16]",
  },
  {
    id: "speaking-6",
    title: "Annual Banquet Presentation",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking6.webp",
    alt: "Banquet keynote presentation",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "speaking-7",
    title: "Youth Leadership Stage",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking7-1536x1181.webp",
    alt: "Players presenting on stage to parents and community",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "speaking-8",
    title: "Storytelling & Personal Journey",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking8.webp",
    alt: "Athlete sharing field hockey journey story",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "speaking-9",
    title: "Public Speaking Workshop",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking9-840x1024.webp",
    alt: "Interactive speaking clinic for youth",
    aspectRatioClass: "aspect-[4/5]",
  },
  {
    id: "speaking-10",
    title: "Team Captain Speech",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking10.webp",
    alt: "Team captain thanking supporters and sponsors",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "speaking-11",
    title: "Overcoming Stage Fright Clinic",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking11-840x1024.webp",
    alt: "Youth athlete practicing speech delivery",
    aspectRatioClass: "aspect-[4/5]",
  },
  {
    id: "speaking-12",
    title: "Graduation & Honors Speech",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking12-1536x1115.webp",
    alt: "Honoring club graduates and award recipients",
    aspectRatioClass: "aspect-[4/3]",
  },
  {
    id: "speaking-13",
    title: "Expressing Gratitude to Coaches",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking13-840x1024.webp",
    alt: "Junior athlete expressing thanks at the mic",
    aspectRatioClass: "aspect-[4/5]",
  },
  {
    id: "speaking-14",
    title: "Voice of the Future Champions",
    category: "public-speaking",
    categoryLabel: "Public Speaking",
    categories: ["public-speaking"],
    image: "/gallery_img/speaking14.webp",
    alt: "Confident youth athlete concluding banquet speech",
    aspectRatioClass: "aspect-[4/3]",
  },
];
